runner-label:
  - "srv649924"
  - "conexao"
  - "conexao-de-sorte-backend-auditoria-compliance"
  - "conexao-de-sorte-backend-autenticacao"
  - "conexao-de-sorte-backend-batepapo"
  - "conexao-de-sorte-backend-chatbot"
  - "conexao-de-sorte-backend-criptografia-kms"
  - "conexao-de-sorte-backend-financeiro"
  - "conexao-de-sorte-backend-gateway"
  - "conexao-de-sorte-backend-notificacoes"
  - "conexao-de-sorte-backend-observabilidade"
  - "conexao-de-sorte-backend-resultados"
  - "conexao-de-sorte-backend-scheduler"
  - "conexao-de-sorte-frontend"
  - "conexao-de-sorte-traefik-infraestrutura"
  - "conexao-de-sorte-zookeeper-infraestrutura"
  - "conexao-de-sorte-kafka-infraestrutura"
  - "conexao-de-sorte-rabbitmq-infraestrutura"
  - "conexao-de-sorte-redis-infraestrutura"
  - "conexao-de-sorte-mysql-infraestrutura"
  - "conexao-de-sorte-jaeger-infraestrutura"