spring:
  application:
    name: auditoria-compliance
    
  profiles:
    default: prod
    
  main:
    allow-bean-definition-overriding: true
    
  # Azure Key Vault (padrão simplificado)
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED:true}
          endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
      profile:
        tenant-id: ${AZURE_TENANT_ID:}
        subscription-id: ${AZURE_SUBSCRIPTION_ID:}
        client-id: ${AZURE_CLIENT_ID:}

  # OAuth2 Resource Server - JWT validation via JWKS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${conexao-de-sorte-jwt-jwks-uri:http://localhost:8081/.well-known/jwks.json}
          issuer-uri: ${conexao-de-sorte-jwt-issuer:https://auth.conexaodesorte.com}

  # R2DBC Configuration (Spring Boot 3.5.5 compatible)
  r2dbc:
    url: ${conexao-de-sorte-database-r2dbc-url:r2dbc:mysql://localhost:3306/conexao_sorte_audit?useSSL=true&allowPublicKeyRetrieval=true}
    username: ${conexao-de-sorte-database-username:audit_user}
    password: ${conexao-de-sorte-database-password:}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: "SELECT 1"
      max-acquire-time: 5s
      max-create-connection-time: 5s

  # Redis Configuration (Spring Boot 3.5.5)
  data:
    redis:
      host: ${conexao-de-sorte-redis-host:localhost}
      port: ${conexao-de-sorte-redis-port:6379}
      password: ${conexao-de-sorte-redis-password:}
      database: ${conexao-de-sorte-redis-database:0}
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 4
          min-idle: 0

  # Flyway for database migrations
  flyway:
    enabled: true
    url: ${conexao-de-sorte-database-jdbc-url:jdbc:mysql://localhost:3306/conexao_sorte_audit}
    user: ${conexao-de-sorte-database-username:audit_user}
    password: ${conexao-de-sorte-database-password:}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

server:
  port: ${conexao-de-sorte-server-port:8085}
  shutdown: graceful
  
  # SSL/TLS Configuration
  ssl:
    enabled: ${conexao-de-sorte-ssl-enabled:false}
    key-store: ${conexao-de-sorte-ssl-keystore-path:}
    key-store-password: ${conexao-de-sorte-ssl-keystore-password:}
    key-store-type: PKCS12
    
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Management endpoints (Spring Boot 3.5.5)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    "[br.tec.facilitaservicos.auditoria]": DEBUG
    "[org.springframework.security]": INFO
    "[org.springframework.r2dbc]": INFO