# ===============================================================================
# AUDITORIA & COMPLIANCE MICROSERVICE - SECURITY-FIRST CONFIGURATION
# ===============================================================================
# Microserviço especializado em auditoria, compliance e logs de segurança
# Segue padrões de segurança defensiva e compliance LGPD/GDPR
# ===============================================================================

spring:
  application:
    name: auditoria-compliance
    
  profiles:
    default: prod
    # Profiles são sobrescritos via SPRING_PROFILES_ACTIVE no deployment
  
  main:
    allow-bean-definition-overriding: true
  
  # Configtree secret management
  config:
    import:
      - optional:configtree:/etc/secrets/azure/
      - optional:configtree:/mnt/secrets/
      - optional:file:./secrets.properties
      
  # Database configuration with security focus
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/conexao_sorte_auditoria}
    username: ${DB_USERNAME:audit_user}
    password: ${DB_PASSWORD:}  # No default password for security
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      pool-name: AuditHikariCP
      
  # JPA Configuration optimized for audit logs
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        jdbc:
          batch_size: 50  # Batch processing for audit log inserts
        generate_statistics: false
        
  # Security JWT for token validation (consumer only)
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:https://auth.conexaodesorte.com}
          audiences: ${JWT_AUDIENCE:conexao-de-sorte}

# Server configuration
server:
  port: ${SERVER_PORT:8085}
  shutdown: graceful
  servlet:
    context-path: /api/v1/audit
  compression:
    enabled: true
  http2:
    enabled: ${HTTP2_ENABLED:true}
    
  # SSL/TLS Configuration
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: PKCS12
  
  # Security error handling
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Audit microservice specific configuration
audit:
  # Data capture configuration
  capture:
    enabled: ${AUDIT_CAPTURE_ENABLED:true}
    include-request-body: ${AUDIT_INCLUDE_REQUEST_BODY:false}  # Security: don't log request bodies
    include-response-body: ${AUDIT_INCLUDE_RESPONSE_BODY:false}  # Security: don't log response bodies
    include-headers: ${AUDIT_INCLUDE_HEADERS:true}
    include-ip: ${AUDIT_INCLUDE_IP:true}
    include-user-agent: ${AUDIT_INCLUDE_USER_AGENT:true}
    
  # Data retention policies (compliance)
  retention:
    default-days: ${AUDIT_RETENTION_DEFAULT:365}  # 1 year
    critical-days: ${AUDIT_RETENTION_CRITICAL:2555}  # 7 years for critical data
    personal-data-days: ${AUDIT_RETENTION_PERSONAL:30}  # LGPD compliance
    authentication-days: ${AUDIT_RETENTION_AUTH:365}
    
  # Audit levels and filtering
  levels:
    authentication: ${AUDIT_LEVEL_AUTH:HIGH}
    authorization: ${AUDIT_LEVEL_AUTHZ:HIGH}
    data-access: ${AUDIT_LEVEL_DATA_ACCESS:MEDIUM}
    data-modification: ${AUDIT_LEVEL_DATA_MOD:HIGH}
    system-changes: ${AUDIT_LEVEL_SYSTEM:CRITICAL}
    errors: ${AUDIT_LEVEL_ERRORS:HIGH}
    
  # Security filters
  filters:
    exclude-health-checks: ${AUDIT_EXCLUDE_HEALTH:true}
    exclude-metrics: ${AUDIT_EXCLUDE_METRICS:true}
    exclude-static-resources: ${AUDIT_EXCLUDE_STATIC:true}
    exclude-patterns: ${AUDIT_EXCLUDE_PATTERNS:/actuator/health,/favicon.ico}
    
  # Security alerts
  alerts:
    enabled: ${AUDIT_ALERTS_ENABLED:true}
    critical-events: ${AUDIT_ALERTS_CRITICAL:true}
    failed-login-threshold: ${AUDIT_FAILED_LOGIN_THRESHOLD:5}
    data-breach-detection: ${AUDIT_DATA_BREACH_DETECTION:true}
    unusual-activity: ${AUDIT_UNUSUAL_ACTIVITY:true}

# Compliance configuration (LGPD/GDPR)
compliance:
  lgpd:
    enabled: ${COMPLIANCE_LGPD_ENABLED:true}
    data-retention-check: ${COMPLIANCE_LGPD_RETENTION_CHECK:true}
    consent-tracking: ${COMPLIANCE_LGPD_CONSENT_TRACKING:true}
    data-portability: ${COMPLIANCE_LGPD_DATA_PORTABILITY:true}
    erasure-requests: ${COMPLIANCE_LGPD_ERASURE:true}
    
  gdpr:
    enabled: ${COMPLIANCE_GDPR_ENABLED:true}
    privacy-by-design: ${COMPLIANCE_GDPR_PRIVACY_DESIGN:true}
    
  reports:
    enabled: ${COMPLIANCE_REPORTS_ENABLED:true}
    schedule: ${COMPLIANCE_REPORTS_SCHEDULE:0 0 1 * *}  # Monthly
    retention-days: ${COMPLIANCE_REPORTS_RETENTION:2555}  # 7 years
    encryption-required: ${COMPLIANCE_REPORTS_ENCRYPTION:true}

# Security monitoring
security:
  monitoring:
    brute-force-detection: ${SECURITY_BRUTE_FORCE_DETECTION:true}
    sql-injection-detection: ${SECURITY_SQL_INJECTION_DETECTION:true}
    xss-detection: ${SECURITY_XSS_DETECTION:true}
    anomaly-detection: ${SECURITY_ANOMALY_DETECTION:true}
    
  # Encryption configuration
  encryption:
    enabled: ${SECURITY_ENCRYPTION_ENABLED:true}
    algorithm: ${SECURITY_ENCRYPTION_ALGORITHM:AES-256-GCM}
    master-key: ${SECURITY_ENCRYPTION_MASTER_KEY:}  # Must be provided via secrets
    
  # Security headers
  headers:
    content-security-policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains; preload"
    referrer-policy: "strict-origin-when-cross-origin"

# CORS Configuration (restrictive for audit service)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://admin.conexaodesorte.com,https://monitoring.conexaodesorte.com}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST}  # Limited methods for audit service
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,X-Requested-With,Accept,Origin}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}

# Rate Limiting (restrictive for audit service)
rate-limit:
  enabled: ${RATE_LIMIT_ENABLED:true}
  default-requests-per-minute: ${RATE_LIMIT_DEFAULT:30}  # Lower limit for audit service
  endpoints:
    "/api/v1/audit/logs":
      requests-per-minute: ${RATE_LIMIT_AUDIT_LOGS:20}
      burst-capacity: ${RATE_LIMIT_AUDIT_LOGS_BURST:30}
    "/api/v1/audit/reports":
      requests-per-minute: ${RATE_LIMIT_AUDIT_REPORTS:10}
      burst-capacity: ${RATE_LIMIT_AUDIT_REPORTS_BURST:15}

# Actuator configuration (security-hardened)
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics,prometheus}
      base-path: /actuator
      cors:
        allowed-origins: ${ACTUATOR_CORS_ORIGINS:https://monitoring.conexaodesorte.com}
        allowed-methods: GET
        
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:when-authorized}
      show-components: ${ACTUATOR_HEALTH_COMPONENTS:when-authorized}
      probes:
        enabled: true
        
  # Security: Disable sensitive endpoints
  info:
    env:
      enabled: false
      
  metrics:
    export:
      prometheus:
        enabled: ${METRICS_PROMETHEUS_ENABLED:true}
    tags:
      service: auditoria-compliance
      environment: ${SPRING_PROFILES_ACTIVE:dev}

# Logging configuration specialized for audit
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    br.tec.facilitaservicos.auditoria: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.springframework.web.filter: ${LOG_LEVEL_WEB_FILTER:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} [AUDIT] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} [AUDIT] [%X{userId:-}] [%X{sessionId:-}] - %msg%n"
    
  file:
    name: ${LOG_FILE:/app/logs/auditoria.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:90}

# OpenAPI Documentation (restricted)
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}  # Disabled by default for security
    
---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
      
  datasource:
    url: jdbc:mysql://localhost:3306/conexao_sorte_auditoria_dev
    
audit:
  capture:
    include-request-body: true  # Enable for development debugging
    
compliance:
  reports:
    schedule: "0 */15 * * * *"  # Every 15 minutes in development
    
logging:
  level:
    br.tec.facilitaservicos.auditoria: DEBUG
    org.springframework.web.filter: DEBUG

---
# Test Profile  
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:audit_test;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    
audit:
  capture:
    enabled: false  # Disable audit capture in tests
    
compliance:
  reports:
    enabled: false  # Disable reports in tests
    
logging:
  level:
    root: WARN
    br.tec.facilitaservicos.auditoria: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:conexao_sorte_auditoria}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
server:
  port: 8085
  ssl:
    enabled: ${SSL_ENABLED:false}
    
audit:
  retention:
    default-days: 365
    critical-days: 2555  # 7 years
    
security:
  encryption:
    enabled: true
    
management:
  endpoint:
    health:
      show-details: never  # Hide health details in production
      
logging:
  level:
    root: WARN
    br.tec.facilitaservicos.auditoria: INFO
    
  file:
    name: /var/log/auditoria/application.log
    
rate-limit:
  default-requests-per-minute: 20  # More restrictive in production