spring:
  r2dbc:
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: "SELECT 1"
      # Configurações adicionais para otimização
      max-acquire-time: 5s # Tempo máximo para adquirir uma conexão do pool
      max-create-connection-time: 5s # Tempo máximo para criar uma nova conexão
      # Configurações de logging para o pool (para depuração)
      # enable-logging: true # Descomente para habilitar logging detalhado do pool

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus