# =============================================================================
# CONFIGURAÇÃO AZURE KEY VAULT - AUDITORIA COMPLIANCE MICROSERVICE (CORRIGIDA)
# =============================================================================
# Microserviço responsável pela auditoria, compliance e logs de segurança
# Compatível com Spring Boot 3.5.5 e Spring Cloud Azure
# Integração completa com todos os segredos solicitados
# =============================================================================

spring:
  config:
    activate:
      on-profile: azure
    import:
      - "optional:configtree:/run/secrets/"

  # ===== SPRING CLOUD AZURE - CONFIGURAÇÃO COMPLETA =====
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED:true}
          endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
      profile:
        tenant-id: ${AZURE_TENANT_ID:}
        subscription-id: ${AZURE_SUBSCRIPTION_ID:}
        client-id: ${AZURE_CLIENT_ID:}

  # ===== R2DBC DATABASE CONFIGURATION =====
  r2dbc:
    url: ${conexao-de-sorte-database-r2dbc-url:${conexao-de-sorte-database-url:r2dbc:mysql://mysql-proxy:6033/conexao_de_sorte?useSSL=true&allowPublicKeyRetrieval=false&serverTimezone=America/Sao_Paulo}}
    username: ${conexao-de-sorte-database-username:audit_user}
    password: ${conexao-de-sorte-database-password:}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s
      max-create-connection-time: 10s
      validation-query: "SELECT 1"

  # ===== FLYWAY FOR MIGRATIONS =====
  flyway:
    enabled: true
    url: ${conexao-de-sorte-database-jdbc-url:jdbc:mysql://mysql-proxy:6033/conexao_de_sorte?useSSL=true&allowPublicKeyRetrieval=false&serverTimezone=America/Sao_Paulo}
    user: ${conexao-de-sorte-database-username:audit_user}
    password: ${conexao-de-sorte-database-password:}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

  # ===== REDIS CONFIGURATION =====
  data:
    redis:
      host: ${conexao-de-sorte-redis-host:conexao-redis}
      port: ${conexao-de-sorte-redis-port:6379}
      password: ${conexao-de-sorte-redis-password:}
      database: ${conexao-de-sorte-redis-database:2}
      timeout: 5s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 5s

  # ===== JWT OAUTH2 CONFIGURATION =====
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${conexao-de-sorte-jwt-issuer:https://auth.conexaodesorte.com}
          jwk-set-uri: ${conexao-de-sorte-jwt-jwks-uri:https://auth.conexaodesorte.com/.well-known/jwks.json}

  # ===== CORS CONFIGURATION =====
  web:
    cors:
      allowed-origins: ${conexao-de-sorte-cors-allowed-origins:http://localhost:3000,https://conexaodesorte.com.br}
      allow-credentials: ${conexao-de-sorte-cors-allow-credentials:true}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      max-age: 3600

# ===== SERVER CONFIGURATION =====
server:
  port: ${conexao-de-sorte-server-port:8085}
  shutdown: graceful

  # SSL/TLS Configuration
  ssl:
    enabled: ${conexao-de-sorte-ssl-enabled:false}
    key-store: ${conexao-de-sorte-ssl-keystore-path:}
    key-store-password: ${conexao-de-sorte-ssl-keystore-password:}
    key-store-type: PKCS12

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

  # Compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

# ===== MANAGEMENT ENDPOINTS =====
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
    env:
      enabled: false
    configprops:
      enabled: false
    beans:
      enabled: false
    conditions:
      enabled: false
    mappings:
      enabled: false
    threaddump:
      enabled: false
    heapdump:
      enabled: false
    startup:
      enabled: false
  health:
    redis:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# ===== JWT CONFIGURATION (COMPLETA) =====
jwt:
  key-id: ${conexao-de-sorte-jwt-key-id:}
  private-key: ${conexao-de-sorte-jwt-privateKey:}
  public-key: ${conexao-de-sorte-jwt-publicKey:}
  secret: ${conexao-de-sorte-jwt-secret:}
  signing-key: ${conexao-de-sorte-jwt-signing-key:}
  verification-key: ${conexao-de-sorte-jwt-verification-key:}
  issuer: ${conexao-de-sorte-jwt-issuer:https://auth.conexaodesorte.com}
  audience: conexao-de-sorte-frontend-app
  algorithm: RS256
  validation:
    enabled: true
    strict-mode: true
    audit-enabled: true

# ===== ENCRYPTION CONFIGURATION =====
encryption:
  master-key: ${conexao-de-sorte-encryption-master-key:}
  master-password: ${conexao-de-sorte-encryption-master-password:}
  backup-key: ${conexao-de-sorte-encryption-backup-key:}
  algorithm: AES-256-GCM
  audit-data:
    encrypt-pii: true
    encrypt-sensitive: true
    encryption-level: HIGH

# ===== AUDITORIA CONFIGURATION =====
auditoria:
  capture:
    enabled: true
    include-request-body: false
    include-response-body: false
    include-headers: true
    include-ip: true
    include-user-agent: true
  retention:
    default-days: 365
    critical-days: 2555
    personal-data-days: 30
  levels:
    authentication: HIGH
    authorization: HIGH
    data-access: MEDIUM
    system-events: LOW

# ===== LOGGING CONFIGURATION =====
logging:
  level:
    root: INFO
    "[br.tec.facilitaservicos.auditoria]": DEBUG
    "[org.springframework.security]": INFO
    "[org.springframework.r2dbc]": DEBUG
    "[org.springframework.cloud.config]": INFO
    "[com.azure.spring]": INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:/app/logs/auditoria-compliance.log}

# ===== SECURITY AUDIT LOGGING =====
security:
  audit:
    enabled: true
    include-request-details: true
    include-client-info: true
    log-authentication-success: true
    log-authentication-failure: true
    log-authorization-failure: true
    audit-all-requests: true
    include-sensitive-data: false
    encrypt-audit-logs: true