spring:
  application:
    name: auditoria-compliance
    
  profiles:
    default: prod
    
  main:
    allow-bean-definition-overriding: true
    
  # Azure Key Vault with manual configuration
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED:true}
          endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
      profile:
        tenant-id: ${AZURE_TENANT_ID:}
        subscription-id: ${AZURE_SUBSCRIPTION_ID:}
        client-id: ${AZURE_CLIENT_ID:}

  # OAuth2 Resource Server - JWT validation via JWKS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:https://auth.conexaodesorte.com}
          audience: ${JWT_AUDIENCE:conexao-de-sorte}

  r2dbc:
    url: ${conexao-de-sorte-database-r2dbc-url:r2dbc:mysql://localhost:3306/conexao_sorte_audit?useSSL=true&allowPublicKeyRetrieval=true}
    username: ${conexao-de-sorte-database-username:}
    password: ${conexao-de-sorte-database-password:}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: "SELECT 1"
      # Configurações adicionais para otimização
      max-acquire-time: 5s # Tempo máximo para adquirir uma conexão do pool
      max-create-connection-time: 5s # Tempo máximo para criar uma nova conexão
      # Configurações de logging para o pool (para depuração)
      # enable-logging: true # Descomente para habilitar logging detalhado do pool

server:
  port: ${conexao-de-sorte-server-port:8084}
  shutdown: graceful
  
  # SSL/TLS Configuration
  ssl:
    enabled: ${conexao-de-sorte-ssl-enabled:false}
    key-store: ${conexao-de-sorte-ssl-keystore-path:}
    key-store-password: ${conexao-de-sorte-ssl-keystore-password:}
    key-store-type: PKCS12
    
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus