# =============================================================================
# CONFIGURAÇÃO PRODUÇÃO - AUDITORIA COMPLIANCE MICROSERVICE
# =============================================================================
# Perfil otimizado para ambiente de produção com foco em performance e segurança
# Compatível com Spring Boot 3.5.5
# =============================================================================

spring:
  config:
    import:
      - optional:configtree:/run/secrets/
      
  # ===== R2DBC POOL CONFIGURATION - PRODUCTION OPTIMIZED =====
  r2dbc:
    pool:
      enabled: true
      initial-size: 15
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 60s
      max-create-connection-time: 10s
      validation-query: "SELECT 1"

  # ===== FLYWAY CONFIGURATION =====
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: true  # Segurança em produção

  # ===== REDIS CONFIGURATION - PRODUCTION =====
  data:
    redis:
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 8
          min-idle: 2
          max-wait: 2s

# ===== LOGGING CONFIGURATION - PRODUCTION =====
logging:
  level:
    root: INFO
    "[br.tec.facilitaservicos.auditoria]": INFO
    "[org.springframework.security]": WARN
    "[org.springframework.r2dbc]": WARN
    "[org.springframework.web]": WARN
    "[com.zaxxer.hikari]": WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} [%X{traceId}] [%X{userId}] - %msg%n"
  file:
    name: /app/logs/auditoria-prod.log
    max-size: 200MB
    max-history: 30

# ===== MANAGEMENT ENDPOINTS - PRODUCTION SECURED =====
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
    info:
      access: read-only
    env:
      access: none
    configprops:
      access: none
  health:
    redis:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60s

# ===== SERVER CONFIGURATION - PRODUCTION =====
server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Fim da configuração de produção
